chore: improve scripts pkg and log

diff --git a/scripts/pkg b/scripts/pkg
--- a/scripts/pkg
+++ b/scripts/pkg
@@ -4,6 +4,14 @@ SCRIPT_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
 
 source "$SCRIPT_DIR/log"
 
+PKG_CONFIG_BLOCK_TOKENS="\
+desc url version filecheck homepage \
+sha256 configflags buildflags \
+preinstall postinstall prebuild \
+postbuild preconfig postconfig \
+testspec patches
+"
+
 # pkg_patchakra dir_patches 
 pkg_patchakra() {
   local os=$HOST_OS
@@ -46,227 +54,298 @@ pkg_patchakra() {
 
 
 
-pkg_parse_config() {
-  local filecontent
-  local pkgconfig
-  local pkgname
-  local args
-  local largs
-  local skip_os
-  local tagpattern="a-z0-9_-"
-  
-  if [ ! -t 0 ]; then
-    filecontent=`cat`
-    args="$@"
-    largs=$(log_get_args $@)
+pkg_config_read_value() {
+  local fd varname tokens temp keepread
+  local btokens="$(tr ' ' '|' <<<$PKG_CONFIG_BLOCK_TOKENS)"
+
+  if [ -t 0 ] || [ -f "$1" ]; then
+    fd=$1
+    varname="$2"
+    tokens="${@:3}"
   else
-    filecontent=$(cat $1)
-    args="${@:2}"
-    largs=$(log_get_args $@)
+    varname="$1"
+    tokens="${@:2}"
+  fi
+
+  if [ -z $tokens ]; then
+    tokens="$btokens"
+  else
+    tokens="$(tr ' ' '|' <<<$tokens)|$btokens"
+  fi
+  while read -r line; do
+    set -- $line
+    if [[ "$1" =~ $tokens ]]; then
+      if [[ "$1" == "$varname" ]]; then
+        if [ ! -z $keepread ]; then
+          log_errexit "Duplicated $1 token"
+        fi
+        keepread=1
+        temp="${@:2}"
+        temp="${temp%\"}"
+        temp="${temp#\"}"
+        echo -ne "$temp\n"
+      else
+        keepread=
+      fi
+    elif [ ! -z $keepread ]; then
+      echo -ne "$line\n"
+    fi
+  done < <(cat $fd)
+}
+
+pkg_config_parse_block() {
+  local fd ctoken bcontent 
+  local varexp varname varvalue
+  local tokens
+  local regex='\${?([a-z]+)\}?'
+
+  if [ -t 0 ] || [ -e "$1" ]; then
+    fd=$1
+    tokens="${@:2}"
+  else
+    tokens="$@"
   fi
   
-  while IFS= read -r line; do
-    if [[ $line == \#* ]]; then 
-      continue
+  while read -r line; do
+    s="$line"
+    while [[ "$line" =~ $regex ]]; do 
+        varexp="${BASH_REMATCH[0]}"
+        varname="${BASH_REMATCH[1]}"
+        varvalue="$(echo -ne "$bcontent" | pkg_config_read_value $varname $tokens)"
+        line="${line//$varexp/$varvalue}"
+        s="${s#*"${BASH_REMATCH[1]}"}"
+    done
+    if [ -z "$bcontent" ]; then 
+      bcontent="$(printf '%s\n' "$line")"
+    else
+      bcontent="$(printf '%s\n%s' "$bcontent" "$line")"
     fi
-    if [[ $line =~ ^(\[([$tagpattern]+)\])$ ]]; then
+
+    echo "$line"
+  done < <(cat $fd)
+}
+
+pkg_args_to_config() {
+  set -- "$@"
+  while [[ $# -gt 0 ]]; do
+    case $1 in
+      --|-)
+        shift 1
+      ;;
+      --*|-*)
+        if [[ "$1" =~ ^-- ]]; then
+          varname=${1#"--"}
+        else
+          varname=${1#"-"}
+        fi
+
+        if [[ "$2" =~ ^--? ]] || [ -z "$2" ]; then
+          echo "$varname true"
+        else
+          echo "$varname $2"
+        fi
+      ;;
+    esac
+    shift 1
+  done
+}
+
+pkg_config_parse() {
+  local fd args largs pkgconfig envconfig pkgname skip_os line tokens
+  local tagpattern='^(\[([a-z0-9_-]+)\])$'
+
+  if [ -t 0 ] || [ -e "$1" ]; then
+    fd=$1
+    args="${@:2}"
+  else
+    args="$@"
+  fi
+  
+  largs=$(log_get_args $@)
+  # parse the incoming flags from args to serialize as 
+  # config to allow variable interpolation
+  envconfig="$(pkg_args_to_config $args)"
+  tokens="$(awk 'NR==1{printf "%s",$1}; NR>1{printf "|%s",$1}' <<< "$envconfig")"
+  log $largs "env tokens detected: $(tr '|' ' ' <<< "$tokens")"
+  
+  while IFS= read -r line || [ -n "$line" ]; do
+    if [ -z "$line" ] || [[ "$line" =~ ^[:space:]*# ]]; then 
+      #ignore comments or empty lines
+      continue
+    elif [[ $line =~ ^(\[([a-z0-9_-]+)\])$ ]]; then
       if [ ! -z $pkgname ]; then 
-        if ! echo -ne $pkgconfig | pkg_build_install $pkgname $args; then
+        # add newline at the end for sanitize block
+        if ! echo -ne "$pkgconfig\n" | pkg_config_parse_block $tokens | pkg_build_install $pkgname $tokens $largs; then
           exit 1
         fi
       fi
-      skip_os=
-      pkgname=${BASH_REMATCH[2]}
-      pkgconfig=
-      log $largs "detected $pkgname config"
-    elif [[ $line =~ ^(\(([$tagpattern]+)\))$ ]]; then
-        log $largs "detected match os expresion for ${BASH_REMATCH[2]}"
-        [[ ${BASH_REMATCH[2]} != $HOST_OS ]] && skip_os=1 || skip_os=
-    elif [[ -z $skip_os ]]; then  
-      [ ! -z "$line" ] && pkgconfig+="$line\n"
+      skip_os= ; pkgconfig="$envconfig" ; pkgname=${BASH_REMATCH[2]}
+      log $largs "detected config for $pkgname"
+    elif [[ $line =~ ^(\(([darwin|linux]+)\))$ ]]; then
+      log $largs "detected match os expresion for ${BASH_REMATCH[2]}"
+      # set flag skip nexts lines until other os tag is detected and matched
+      [[ ${BASH_REMATCH[2]} != $HOST_OS ]] && skip_os=1 || skip_os=
+    elif [[ -z $skip_os ]]; then
+      if [ -z "$pkgconfig" ]; then 
+        pkgconfig="$(printf '%s\n' "$line")"
+      else
+        pkgconfig="$(printf '%s\n%s' "$pkgconfig" "$line")"
+      fi
+    else
+      log $largs "skipping config line $line"
     fi
-  done < <(echo -ne "$filecontent")
+  done < <(cat $fd)
 
-  if [ ! -z $pkgname ]; then 
-    echo -ne $pkgconfig | pkg_build_install $pkgname $args
+  if [ ! -z $pkgname ]; then
+    echo -ne "$pkgconfig\n" | pkg_config_parse_block $tokens | pkg_build_install $pkgname $tokens $largs
   fi
 }
 
 pkg_build_install() {
-  local pkgname ctoken tcontent args pkgconfig sources \
-        filename tmpdir patchesdir toolchaindir
-  local cflags=$(echo $@|awk -F' -- ' '{ print $2 }')
+  local fd args tokens envconfig \
+        pkgname pkgconfig \
+        sources filename extension \
+        getval
+  #local cflags=$(echo $@|awk -F' -- ' '{ print $2 }')
   local largs=$(log_get_args $@)
-  local pkgargs=$(log_exclude_args $@)
   local dryrun=$(is_flag_present --dry-run $@)
-  
-  set -- $pkgargs
-  
-  if [ ! -t 0 ]; then
-    pkgname="$1"
-    pkgconfig="$(cat)"
-    shift 1
-  elif [ -e "$1" ]; then
-    pkgname="$2"
-    pkgconfig="$(cat "$1")"
-    shift 2
-  else
-    log_errexit $largs "Error a config must be provided" 
-  fi
 
+  if [ -t 0 ] || [ -e "$1" ]; then
+    fd="$1"
+    pkgname="$2"
+    tokens="$3"
+  else
+    pkgname="$1"
+    tokens="$2"
+  fi
+  
+  if [ -z "$pkgname" ]; then
+    log $largs --err "Empty package name\n" 
+    log_errexit "The process can't continue due a package name must be provided"
+  fi
+  
+  pkgconfig="$(cat $fd)"
+  # create a custom function to extract the values from pkgconfig
+  eval $"function pkg_config_block_read_value() {
+    pkg_config_read_value \$1 "\"\$tokens\"" <<< "\"\$pkgconfig\"";
+  }"
+  
+  local tempdir="$(pkg_config_block_read_value tempdir)"
+  local toolchaindir="$(pkg_config_block_read_value toolchaindir)"
+  local url="$(pkg_config_block_read_value url)"
+  local filecheck="$(pkg_config_block_read_value filecheck)"
+  
   log $largs <(echo -ne "config details:\n$(echo -ne "$pkgconfig"|sed -e 's/^/-> /')")
   
-  while [[ $# -gt 0 ]]; do
-    case $1 in
-      -t|--tempdir)
-        tmpdir="$2"
-        shift 2
-      ;;
-      -T|--toolchaindir)
-        toolchaindir="$2"
-        shift 2
-      ;;
-      -p|--patchesdir)
-        patchesdir="$2"
-        shift 2
-      ;;
-      -D|--download-flags)
-        dflags="$2"
-        shift 2
-      ;;
-      --)
-        break
-      ;;
-      *)
-        break;
-      ;;
-    esac
-  done 
-
-  sources=${pkgname}_src
-  
-  if [ -z "$tmpdir" ]; then
-    log $largs --err "Temporary directory must be defined\n" 
+  if [ -z "$tempdir" ]; then
+    log $largs --err "Temporary directory must be defined" 
     log_errexit "The process can't continue due a temporary diretory must be provided"
   fi
 
-  if [ ! -d "$tmpdir" ]; then
+  if [ ! -d "$tempdir" ]; then
     log $largs --err "Temporary directory must exists\n" 
-    log_errexit "The process can't continue due a temporary diretory is not exist check $tmpdir"
+    log_errexit "The process can't continue due a temporary diretory is not exist check $tempdir"
   fi
-  
-  while read -r line; do
-    set -- $line
-    case $1 in 
-      url|version|filecheck|homepage|\
-      sha256|configflags|buildflags|\
-      preinstall|postinstall|prebuild|\
-      postbuild|preconfig|postconfig|\
-      testspec|patches)
-        if [ ! -z "$ctoken" ]; then
-          tcontent="$(eval "\
-            export toolchaindir="${toolchaindir}"; \
-            export version="${version}"; \
-            echo -ne '$tcontent'")"
-          # nasty way to create dynamic variable due 
-          # there's no way to make an associative array in bash 3
-          eval "local $ctoken="\"$tcontent\"""
-        fi
-        ctoken="$1"
-        tcontent="${@:2}"
-      ;;
-      \#*)
-        #ignore comments
-      ;;
-      *)
-        tcontent+="\n$line"
-      ;;
-    esac 
-  done < <(echo -ne "$pkgconfig")
-  
-  if [ ! -z "$ctoken" ]; then
-    eval "local $ctoken="\"$tcontent\"""
-  fi
-  
+
+  sources=${pkgname}_src
   filename="${url##*/}"
   extension=${url##*.}
 
-  log $largs "using temporary directory $tmpdir"
-  log_wrap $largs -- pushd $tmpdir
+  log $largs "using temporary directory $tempdir"
+  log_wrap $largs -- pushd $tempdir
 
   log $largs "using toolchain directory $toolchaindir"
   mkdir -p $toolchaindir
   
   log $largs --header "Installing $pkgname"
   
-  if [ ! -z "$filecheck" ] && ls $filecheck &>/dev/null; then
-    log $largs --ok "already installed $pkgname"
+  if [ ! -z "$filecheck" ] && eval ls $filecheck &>/dev/null; then
+    log $largs --ok "already installed"
     return 0
   fi
   
   if [ ! -d $sources ]; then
     if [ "$extension" == "git" ]; then
-      pkg_clone $url $sources $version $largs
+      pkg_clone $largs $sources
     elif [ ! -f $filename ]; then 
-      pkg_download $url $filename $largs
-      if [ ! -z $sha256 ]; then
-        pkg_verify_checksum $filename $sha256 $largs
-      fi
+      pkg_download $largs $filename
+      pkg_verify_checksum $largs $filename
     fi
   fi
   
-  ## Unpacking
+  
   if [ ! -d $sources ] && [[ $extension == *"z"* ]]; then
     pkg_unpack $filename $sources $largs
   fi
 
-  ## Patching
-  if [ ! -z "$patches" ]; then
-    log_wrap $largs -- pushd $sources
-    pkg_patchakra $patches
-    log_wrap $largs -- popd
-  fi
+  log_wrap $largs -- pushd $sources
 
-  [ -z $dryrun ] && pushd $sources > /dev/null
-
-  if [ ! -z "$preconfig" ]; then
-    log_wrap_process $largs "pre-configure" -- \
-      "$preconfig"
-  fi
-
-  pkg_configure $toolchaindir $configflags $largs
-
-  if [ ! -z "$postconfig" ]; then
-    log_wrap_process $largs "post configure" -- \
-      "$postconfig"
-  fi
-
-  if [ ! -z $prebuild ]; then
-    log_wrap_process $largs "pre-build" -- \
-      "$prebuild"
-  fi
-
+  pkg_patch $largs
+  pkg_configure $largs
   pkg_build $largs
+  pkg_install $largs
+  pkg_test $largs
+}
 
-  if [ ! -z $postbuild ]; then
-    log_wrap_process $largs "post-build" -- \
-      "$postbuild"
-  fi
-
-  if [ ! -z $preinstall ]; then
-    log_wrap_process $largs "pre-install" -- \
-      "$preinstall"
-  fi
-
-  pkg_install $toolchaindir $largs
+pkg_clone() {
+  local largs=$(log_get_args $@)
+  local args=$(log_exclude_args $@)
+  local url="$(pkg_config_block_read_value url)"
+  local version="$(pkg_config_block_read_value version)"
   
-  if [ ! -z $postinstall ]; then
-    log_wrap_process $largs "post-install" -- \
-      "$postinstall"
+  if [ ! -z $version ]; then 
+    args=" --single-branch --branch $version"
+  fi
+  
+  log_wrap_process $largs "fetch sources from $url" -- git clone $args $url
+}
+
+pkg_download() {
+  local largs=$(log_get_args $@)
+  local args=$(log_exclude_args $@)
+  local url="$(pkg_config_block_read_value url)"
+  set -- $args
+  
+  trap "echo -ne >&2 '\n\nAborting, removing $1\n\n'; rm -f $1; exit 1" INT
+  log_wrap_progress $largs --strip 1 "download $1" -- wget \
+    --no-clobber \
+    --quiet \
+    --show-progress \
+    --progress=bar:force \
+    --output-document=$1 \
+    "${@:2}" \
+    $url
+}
+
+pkg_verify_checksum() {
+  local sha256="$(pkg_config_block_read_value sha256)"
+  local largs=$(log_get_args $@)
+  local args=$(log_exclude_args $@)
+  local dryrun=$(is_flag_present --dry-run $@)
+
+  if [ -z $sha256 ]; then
+    return 0
   fi
 
-  if [ ! -z "$testspec" ]; then
-    log_wrap_process $largs "testing $pkgname" -- "$testspec"
+  set -- $args
+  local cmd="shasum -a 256 $1 | awk '{ print \$1}'"
+
+  if [ ! -z $dryrun ]; then
+    echo $cmd
+    return 0
+  fi
+  local checksum=$(eval $cmd)
+  if [[ $checksum = $sha256 ]]; then
+    log --ok $largs "check sha256sum $checksum"
+  else
+    log --err $largs "check sha256sum $checksum"
+    log_errexit $largs <(cat <<-EOF
+Wrong signature
+  Actual: $checksum
+  Expected: $sha256
+
+EOF
+)
   fi
 }
 
@@ -291,7 +370,7 @@ pkg_unpack() {
   log_wrap $largs -- mkdir -p $2
   log_wrap $largs -- pushd $2
   trap "echo -ne >&2 '\n\nAborting, removing $2\n\n'; rm -rf $2; exit 1" INT
-  if ! log_wrap_progress $largs --strip 2 "unpack" -- \
+  if ! log_wrap_progress $largs --strip 2 "unpack $1" -- \
       tar v --strip-components 1 -xf "../$1" ; then
     log_wrap $largs -- popd
     log_wrap $largs -- rm -rf $2
@@ -299,111 +378,118 @@ pkg_unpack() {
   log_wrap $largs -- popd
 }
 
-pkg_build() {
+pkg_patch() {
   local largs=$(log_get_args $@)
-  local args=$(log_exclude_args $@)
-  local nproc=$(type nproc &> /dev/null && nproc || sysctl -n hw.ncpu)
-  set -- $args
-
-  if [ -f build/Makefile ] || [ -f Makefile ]; then
-    log_wrap $largs -- pushd $(dirname $(ls {build,.}/Makefile 2>/dev/null))
-    log_wrap_process $largs "build" -- make -j$nproc $@
-    log_wrap $largs -- popd
-  fi  
-}
-
-pkg_install(){
-  local largs=$(log_get_args $@)
-  local args=$(log_exclude_args $@)
-  set -- $args
-
-  if ls {bin,lib} &>/dev/null; then
-    log_wrap_progress $largs "install" -- $(os_get_bin_path rsync) -vrzLR {bin,lib} "$1/"
-  elif [ -f build/Makefile ] || [ -f Makefile ]; then
-    log_wrap $largs -- pushd $(dirname $(ls {build,.}/Makefile 2>/dev/null))
-    log_wrap_process $largs "install" -- make install
-    log_wrap $largs -- popd
+  local args="$(log_exclude_args $@)"
+  local patches="$(pkg_config_block_read_value patches)"
+  
+  if [ ! -z "$patches" ]; then
+    pkg_patchakra $patches $args
   fi
 }
-
 pkg_configure() {
+  local exit_code=0
   local largs=$(log_get_args $@)
-  local args=$(log_exclude_args $@)
-  local exit_code
-  set -- $args
+  local args="$(log_exclude_args $@)"
+  local configflags="$(pkg_config_block_read_value configflags)"
+  local prefix="$(pkg_config_block_read_value toolchaindir)"
+  local preconfig="$(pkg_config_block_read_value preconfig)"
+  local postconfig="$(pkg_config_block_read_value postconfig)"
 
+  # exit
+  if [ ! -z "$preconfig" ]; then
+    log_wrap_process $largs "pre-configure" -- \
+      "$(echo -ne $preconfig)"
+  fi
+  
   if [ -f CMakeLists.txt ]; then
     log_wrap $largs -- mkdir -p build
     log_wrap $largs -- pushd build
     log_wrap_process $largs "configure" -- \
-      cmake .. -DCMAKE_INSTALL_PREFIX:PATH="${1}" ${@:2}
+      cmake .. \
+        -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG \
+        -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG \
+        -DCMAKE_INSTALL_PREFIX="$prefix" \
+        -DCMAKE_BUILD_TYPE=Release \
+        -DCMAKE_FIND_FRAMEWORK=LAST \
+        -DCMAKE_VERBOSE_MAKEFILE=ON \
+        -DCMAKE_SYSROOT="$prefix" \
+        -Wno-dev \
+        "$(echo -ne $configflags)"
     exit_code=$?
     log_wrap $largs -- pushd
   elif [ -f configure ]; then
     mkdir -p build
     log_wrap $largs -- pushd build
     log_wrap_process $largs "configure" -- \
-      ../configure --prefix="$1" ${@:2}
+      ../configure --prefix="$prefix" \
+      "$(echo -ne $configflags)"
     exit_code=$?
     log_wrap $largs -- popd
+  fi
+
+  if [ ! -z "$postconfig" ]; then
+    log_wrap_process $largs "post configure" -- \
+      "$(echo -ne $postconfig)"
   fi
 
   return $exit_code
 }
 
-pkg_clone() {
+pkg_build() {
   local largs=$(log_get_args $@)
-  local args=$(log_exclude_args $@)
-  local dryrun=$(is_flag_present --dry-run $@)
-  set -- $args
-  log_wrap_process $largs "fetch sources from $1" -- git clone $1 $2
+  local prebuild="$(pkg_config_block_read_value prebuild)"
+  local postbuild="$(pkg_config_block_read_value postbuild)"
+  local nproc=$(type nproc &> /dev/null && nproc || sysctl -n hw.ncpu)
 
-  if [ ! -z $3 ]; then
-    log_wrap $largs -- pushd $2
-    log_wrap_process $largs "select branch $1" -- git checkout $3
+  if [ ! -z $prebuild ]; then
+    log_wrap_process $largs "pre-build" -- \
+      "$prebuild"
+  fi
+
+  if [ -f build/Makefile ] || [ -f Makefile ]; then
+    log_wrap $largs -- pushd $(dirname $(ls {build,.}/Makefile 2>/dev/null))
+    log_wrap_process $largs "build" -- make -j$nproc
+    log_wrap $largs -- popd
+  fi  
+
+  if [ ! -z $postbuild ]; then
+    log_wrap_process $largs "post-build" -- \
+      "$postbuild"
+  fi
+}
+
+pkg_install() {
+  local largs=$(log_get_args $@)
+  local preinstall="$(pkg_config_block_read_value preinstall)"
+  local postinstall="$(pkg_config_block_read_value postinstall)"
+  local toolchaindir="$(pkg_config_block_read_value toolchaindir)"
+
+  if [ ! -z $preinstall ]; then
+    log_wrap_process $largs "pre-install" -- \
+      "$preinstall"
+  fi
+
+  if ls {bin,lib} &>/dev/null; then
+    log_wrap_progress $largs "install" -- $(os_get_bin_path rsync) -vrzLR {bin,lib} "$toolchaindir/"
+  elif [ -f build/Makefile ] || [ -f Makefile ]; then
+    log_wrap $largs -- pushd $(dirname $(ls {build,.}/Makefile 2>/dev/null))
+    log_wrap_process $largs "install" -- make install
     log_wrap $largs -- popd
   fi
-}
 
-pkg_download() {
-  local largs=$(log_get_args $@)
-  local args=$(log_exclude_args $@)
-  
-  set -- $args
-  trap "echo -ne >&2 '\n\nAborting, removing $2\n\n'; rm -f $2; exit 1" INT
-  log_wrap_progress $largs --strip 1 "download" -- wget \
-    --no-clobber \
-    --quiet \
-    --show-progress \
-    --progress=bar:force \
-    --output-document=$2 \
-    ${@:3} \
-    $1
-}
-
-pkg_verify_checksum() {
-  local largs=$(log_get_args $@)
-  local dryrun=$(is_flag_present --dry-run $@)
-  local args=$(log_exclude_args $@)
-  set -- $args
-  local cmd="shasum -a 256 $1 | awk '{ print \$1}'"
-
-  if [ ! -z $dryrun ]; then
-    echo $cmd
-    return 0
+  if [ ! -z $postinstall ]; then
+    log_wrap_process $largs "post-install" -- \
+      "$postinstall"
   fi
-  local checksum=$(eval $cmd)
-  echo "checksum $checksum"
-  if [[ $checksum = $2 ]]; then
-    log --ok $largs "check sha256sum"
-  else
-    log --err $largs "check sha256sum"
-    log_errexit $largs <(cat <<-EOF
-Wrong signature
-  Actual: $checksum
-  Expected: $2
+}
 
-EOF
-)
+pkg_test() {
+  local largs=$(log_get_args $@)
+  local args=$(log_exclude_args $@)
+  local testspec="$(pkg_config_block_read_value testspec)"
+  
+  if [ ! -z "$testspec" ]; then
+    log_wrap_process $largs "testing" -- "$testspec $args" 
   fi
 }
